services:
  - type: web
    name: fitflex-backend
    env: java
    buildCommand: ./build.sh
    startCommand: java -jar target/maven.demo-0.0.1-SNAPSHOT.jar
    plan: free
    branch: main
    autoDeploy: true