services:
  - type: web
    name: fitflex-backend
    runtime: java
    buildCommand: mvn clean package
    startCommand: java -cp target/maven.demo-0.0.1-SNAPSHOT.jar app.Aplicacao
    plan: free
    envVars:
      - key: PORT
        value: 8080
