services:
  - type: web
    name: fitflex-backend
    runtime: java
    buildCommand: mvn clean package
    startCommand: java -jar target/fitflex-backend-1.0-SNAPSHOT.jar
    plan: free
    envVars:
      - key: PORT
        value: 8080
